# The title to display above the header for your page
title: Junteng Liu

# The URL of the site with a leading slash
url: https://juntengliu.github.io/

# The base URL of your site (e.g., /blog)
baseurl: /LJT-Homepage

# Don't trim your site's trailing slashes
trim_trailing_slash: true

# The name appears next to tags in the header
author: Junteng Liu

# The email address used for meta tags and error pages
email: jliugi@connect.ust.hk

# The description appears in the site metadata tags
description: Just a personal page

descriptioni: Just a personal page

# Social media links
social:
  name: Junteng Liu
  email: jliugi@connect.ust.hk
  twitter: junteng88716710
  github: Vicent0205
  google_scholar: prof.google.com/citations?hl=en&user=tbK9jl4AAAAJ

# Navigation
nav:
  - name: Home
    url: /
  - name: About
    url: /about/
  - name: Publications
    url: /publications/
  - name: Contact
    url: /contact/

# Header configuration
header:
  tab1: Home
  tab2: About
  tab3: Publications
  tab4: Contact
  logo: ""

footer:
  row1:
    - title: "发表"
      link: "#"
    - title: "Teaching"
      link: "#"
    - title: "TCM"
      link: "#"
  row2:
    - title: "Privacy Policy"
      link: "#"
    - title: "Terms of Use"
      link: "#"
  copyright: "Copyright 2017-202X <a href="https://juntengliu.github.io/LJT-Homepage"><span class="icon">&#9935;</span> Junteng Liu</a>"

# Keywords for SEO
keywords: "Homepage, Academic, Junteng Liu, Machine Learning, NLP, Deep Learning, LLM, Reinforcement Learning"

permalink: /blog/:year/:month/:title/

# Jekyll config
jekyll:
  safe: false

# Coverage plugins
google_analytics: _ga_tracking_id
umami: _umami_url
announcement: _announcement
redirect: _redirect

# Analytics
analytics:
  provider: google
  google:
    tracking_id: _ga_tracking_id

# Comments
comments:
  - disqus

# Site built with
sitebuiltwith:
  - jekyll
  - twitter-bootstrap